version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
