import type { OpportunityListItem } from "./types";

export const demoOpportunities: readonly OpportunityListItem[] = [
  {
    id: "demo-1",
    organization: "Northstar Manufacturing",
    country: "FR",
    family: "buying_intent",
    recommendedOffer: "SIEM / CMDR discovery workshop",
    score: 86,
    confidence: 91,
    trigger: "Public tender and three recent SOC engineering job posts",
    evidenceAge: "42 min",
    relevantRoles: ["RSSI", "Head of SOC", "Achats IT"],
    state: "needs_review",
    nextAction: "Review tender scope",
  },
  {
    id: "demo-2",
    organization: "Alpine Health Services",
    country: "CH",
    family: "crisis",
    recommendedOffer: "Incident-response readiness review",
    score: 74,
    confidence: 62,
    trigger: "Unconfirmed ransomware claim with no official statement",
    evidenceAge: "18 min",
    relevantRoles: ["CISO", "CIO", "Legal"],
    state: "monitoring",
    nextAction: "Wait for independent confirmation",
    warning: "Claim only — outreach blocked",
  },
  {
    id: "demo-3",
    organization: "Harbor Retail Group",
    country: "BE",
    family: "renewal",
    recommendedOffer: "SOC and SIEM replacement assessment",
    score: 79,
    confidence: 83,
    trigger: "Public contract enters estimated renewal window in 90 days",
    evidenceAge: "1 day",
    relevantRoles: ["CIO", "SOC Manager", "Procurement"],
    state: "qualified",
    nextAction: "Validate incumbent and renewal options",
  },
];
